name: Testes ItauBot CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test_itaubot:
    runs-on: windows-itaubot
  
    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4

      - name: 🛠️ Configurar PATH do Python Local
        run: |
          $PythonBase = "C:\Users\Pedro\AppData\Local\Programs\Python\Python311"
          echo "$PythonBase" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "$PythonBase\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append
          
      - name: 💬 Configurar Encoding (chcp 65001)
        run: chcp 65001

      - name: 📦 Instalar Dependências do Projeto
        run: |
          # 1. Tenta instalar o pipenv
          python -m pip install --upgrade pip
          python -m pip install pipenv
          
          # 🚨 2. Instala dependências, contornando os erros de ambiente:
          # A) '--insecure' e '--trusted-host': IGNORA O ERRO SSL/HTTPS (Temporário)
          # B) '2>&1 | Out-Host': Ajuda a resolver o UnicodeDecodeError (como última tentativa)
          # C) Adiciona o ENCODING de FORMA EXPLÍCITA (ajuda contra UnicodeError)
          $env:PYTHONIOENCODING="cp1252"
          
          pipenv install --dev --deploy --system --extra-pip-args "--trusted-host pypi.org --trusted-host files.pythonhosted.org --insecure" 2>&1 | Out-Host

      - name: 🌐 Instalar Browsers do Playwright
        run: |
          pipenv run playwright install --with-deps

      - name: ▶️ Executar Testes Pytest
        env:
          OPERATOR_ITAU: ${{ secrets.OPERATOR_ITAU }}
          PASSWORD_ITAU: ${{ secrets.PASSWORD_ITAU }}
        run: |
          pipenv run pytest src/tests/test_login.py
